// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTRPGManager.Data;

#nullable disable

namespace TTRPGManager.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    [Migration("20260501201101_AddMapsTable")]
    partial class AddMapsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("TTRPGManager.Models.BaseCreature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alignment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CasterLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CastingStat")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ChallengeRating")
                        .HasColumnType("REAL");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCharismaProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasConstitutionProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDexterityProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasIntelligenceProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasShield")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasStrengthProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWisdomProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HitDice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InitiativeBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManualACValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PassivePerception")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Portrait")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel7")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel8")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellSlotsLevel9")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseManualAC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BaseCreatures");

                    b.HasDiscriminator().HasValue("BaseCreature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TTRPGManager.Models.ConditionImmunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("ConditionImmunity");
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbilityStatType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageDice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LegendaryActionCost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MiscDamageBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("CreatureAbility");
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomLanguage")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedLanguage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("CreatureLanguage");
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OverrideBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skill")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("CreatureSkill");
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Components")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageDice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCantrip")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConcentration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("School")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("CreatureSpells");
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureTrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraitDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("CreatureTrait");
                });

            modelBuilder.Entity("TTRPGManager.Models.DamageModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Modifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("DamageModifier");
                });

            modelBuilder.Entity("TTRPGManager.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArmorClassValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArmorType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageDice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinesseWeapon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMagical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TTRPGManager.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("GridScale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlayerSafe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("TTRPGManager.Models.MovementSpeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AbleToHover")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCreatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCreatureId");

                    b.ToTable("MovementSpeed");
                });

            modelBuilder.Entity("TTRPGManager.Models.Enemy", b =>
                {
                    b.HasBaseType("TTRPGManager.Models.BaseCreature");

                    b.HasDiscriminator().HasValue("Enemy");
                });

            modelBuilder.Entity("TTRPGManager.Models.Npc", b =>
                {
                    b.HasBaseType("TTRPGManager.Models.BaseCreature");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Npc");
                });

            modelBuilder.Entity("TTRPGManager.Models.ConditionImmunity", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Conditions")
                        .HasForeignKey("BaseCreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureAbility", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Abilities")
                        .HasForeignKey("BaseCreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureLanguage", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Languages")
                        .HasForeignKey("BaseCreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureSkill", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Skills")
                        .HasForeignKey("BaseCreatureId");
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureSpell", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Spells")
                        .HasForeignKey("BaseCreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTRPGManager.Models.CreatureTrait", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Traits")
                        .HasForeignKey("BaseCreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTRPGManager.Models.DamageModifier", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("BaseCreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTRPGManager.Models.Item", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Inventory")
                        .HasForeignKey("BaseCreatureId");
                });

            modelBuilder.Entity("TTRPGManager.Models.MovementSpeed", b =>
                {
                    b.HasOne("TTRPGManager.Models.BaseCreature", null)
                        .WithMany("Speeds")
                        .HasForeignKey("BaseCreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTRPGManager.Models.BaseCreature", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Conditions");

                    b.Navigation("Inventory");

                    b.Navigation("Languages");

                    b.Navigation("Modifiers");

                    b.Navigation("Skills");

                    b.Navigation("Speeds");

                    b.Navigation("Spells");

                    b.Navigation("Traits");
                });
#pragma warning restore 612, 618
        }
    }
}
